### ISSUE TITLE
Booleans and enums represented as 0 show up as null in JSON

### ISSUE THREAD

**Issue by markusjevringgoeuro** [HubSpot/jackson-datatype-protobuf#12]
This happens for both enums (which are indexed starting at 0) and booleans (where 0 represents false).
When I serialize objects with booleans, I always only get `true` or `null`.
When I serialize objects with enums, I always only get values that have index 1 or higher.

I'm using protocol buffers 3.0. I know the objects are correct until the point where it's time to convert them into JSON.

**Comment by markusjevringgoeuro** [comment]
After some digging, this happens in ProtobufSerializer.serialize(), when, on line 57, you check `message.hasField(field)`, this returns `false` because the value is the same as the default. When this happens, you write null instead of the actual value. 
I think this is an unfortunate quirk of version 3 of protocol buffers. I think that, to support version 3, you might have to simply omit that check. Or at least make it optional/configurable somehow.

**Comment by jhaber** [comment]
Thanks for the issue! I haven't done any testing with protobuf 3 but there is a good amount of unit test coverage so I'll try bumping the protobuf-java dependency to 3.0.0 and get the tests passing

**Comment by jhaber** [comment]
However, if you're using Protobuf 3 I think this library is largely obsoleted by the native JSON support they added. Do you think that could work for you or are you worried about the JSON representation changing?

**Comment by markusjevringgoeuro** [comment]
I wasn't aware of native JSON support for proto3. Do you have a link to this? 
This is a greenfield project, so I can change the representation any way I choose. I just liked using Jackson =)

**Comment by jhaber** [comment]
The representation is covered in the language guide [here](https://developers.google.com/protocol-buffers/docs/proto3#json) and it seems like to actually use it you'd want to look at the [JsonFormat](https://github.com/google/protobuf/blob/2078f614e46e78ed425da255fe0c12ced58e3c15/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java) class. I'm thinking for Protobuf 3 we could still have a Jackson serializer/deserializer but they would just be a thin wrapper around JsonFormat. I can try to whip this up at some point today.

**Comment by markusjevringgoeuro** [comment]
This is very interesting. I'm going to have to try this out. =)

**Comment by jhaber** [comment]
I just pushed a `protobuf3` branch, let me know if it works for you. Unfortunately, because we delegate the serialization/deserialization now we don't have the ability to respect the Jackson configuration. Previously we respected:

- the JsonInclusion settings
- `DeserializationFeature.FAIL_ON_NUMBERS_FOR_ENUMS`
- `DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL` 
- custom property naming strategies
- `SerializationFeature.WRITE_EMPTY_JSON_ARRAYS`
- `DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES`
- `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES`
- `SerializationFeature.WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED`
- `SerializationFeature.WRITE_ENUMS_USING_INDEX`
- `DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY` 
- custom Serializers/Deserializers for nested messages

So I had to remove a bunch of tests that will no longer pass.

**Comment by cowtowncoder** [comment]
On protobuf3, it may still make sense to have Jackson-datatype support if non-JSON-non-protobuf formats are to be supported, so that protoc representation may be serialized as XML, CSV, YAML, CBOR, Smile, Properties or Avro.
Wrt JSON it may be of less useful although Jackson configurability could allow better json output even if proto3 library has its own serialization support.

**Comment by jhaber** [comment]
That's true, also the wrapper around the native protobuf3 JSON support didn't turn out nearly as nicely as I had hoped. On the [serialization side](https://github.com/HubSpot/jackson-datatype-protobuf/blob/329b8beaeaa83af25de21c07844aee08cf97dc5d/src/main/java/com/hubspot/jackson/datatype/protobuf/ProtobufSerializer.java#L32-L38) I use `writeRaw` if possible, otherwise I fall back to writing the object as a string, reading that string as a JSON tree, and writing that tree to the generator. On the [deserialization side](https://github.com/HubSpot/jackson-datatype-protobuf/blob/329b8beaeaa83af25de21c07844aee08cf97dc5d/src/main/java/com/hubspot/jackson/datatype/protobuf/ProtobufDeserializer.java#L60-L68) they want me to pass a `Reader` so I try to use the input source directly and fall back to reading the value as a tree, converting it to a string, and wrapping it in a `Reader`.

So in a nut shell you lose the Jackson configurability and potentially lose inter-operability with the other formats. On the other hand, if protobufs now have a canonical JSON representation maybe we should be using it. But it seems like the native JSON printer does have configuration options so the representation is still configurable, just not nearly to the same extent that Jackson allows. My inclination at this point is to not use the native JSON support and instead try to get the existing code working with protobuf3, but supporting some of the new features like `Any` will be challenging

**Comment by markusjevringgoeuro** [comment]
I'll give that branch a try. Thanks.

**Comment by markusjevringgoeuro** [comment]
Unfortunately I can't get it to compile. It tells me 
> Fatal Error: Unable to find package java.lang in classpath or bootclasspath

Everything else I compile works just fine. Not sure where the error is hidden =(
I tried to poke around with it a bit, but to no avail. I'll try more, but at least you know.

**Comment by markusjevringgoeuro** [comment]
After hacking and slashing my way through the pom.xml, I finally got it to compile. Unfortunately it still doesn't work, but for different reasons. Whereas in the past, default values would come out as null, now they simply don't come out at all. Any boolean set to `false` is simply not present in the output. Same with default value enums.

**Comment by markusjevringgoeuro** [comment]
Also lost is support for custom serializers. I had custom jackson serializers for my protocol buffer date classes, for instance. It might be better to simply add manual support for proto3 to the existing library, and skip the native JSON implementation from protocol buffers.

**Comment by markusjevringgoeuro** [comment]
According to https://developers.google.com/protocol-buffers/docs/proto3#json
> If a field has the default value in the protocol buffer, it will be omitted in the JSON-encoded data by default to save space.

This is fixable by doing this:
`JsonFormat.printer().includingDefaultValueFields()` wherever we need a Printer.

**Comment by markusjevringgoeuro** [comment]
Not sure how to do custom serializers for contained types, however.

**Comment by markusjevringgoeuro** [comment]
I've been playing around with it a bit, and I don't think I can get custom formatting of objects without switching either entirely or partially go Gson, which is what protocol buffers actually uses for their JSON formatting. Have you had any luck simply supporting proto3 in your original implementation?

**Comment by Andy-L** [comment]
I'd like to vote in favor of keeping jackson support for proto3; I'm working with some code that uses proto3 for some objects but not all, so having a single consistent way (Jackson) to serialize everything to JSON is valuable.

**Comment by jhaber** [comment]
I'm thinking we'll have separate versions of the library for proto2 vs. proto3, probably maintained on separate branches

**Comment by jhaber** [comment]
Sorry for the long delay. I just released a version of the library with support for Protobuf 3. More detail can be found [here](https://github.com/HubSpot/jackson-datatype-protobuf/blob/jackson29-proto3/README.md#protobuf-3-support). It should fix this issue with Boolean and enum serialization.
