### ISSUE TITLE
StringValue is serialized only to string, not a value object

### ISSUE THREAD

**Issue by floofy** [HubSpot/jackson-datatype-protobuf#80]
When a StringValue.class is encountered, the serialized output becomes `{ "name": "John Doe" }`, instead of `{ "name": { "value": "John Doe" } }`. 

The protobuf definition of a StringValue defined in `package google.protobuf` is:

```
// Wrapper message for `string`.
//
// The JSON representation for `StringValue` is JSON string.
message StringValue {
  // The string value.
  string value = 1;
}
```

For my use case, at least through an optional feature, I need to get the exact structure of the Protobuf message as defined in the proto definition. 

I'm not sure if this is similar or same to issue #78

Environment:
---
**Platform:** Java 11
**jackson-databind:** 2.12.2
**jackson-datatype-protobuf:** 0.9.12

**Comment by jhaber** [comment]
👋 I believe all of these built-in "wrapper" types are supposed to serialize directly as the underlying value, rather than an object. If you don't want this behavior, some options are:
- make your own protobuf message that wraps a string, it will serialize as an object
- if you want to make this change globally, you can register a custom serializer/deserializer for `StringValue` (after installing `ProtobufModule`, so that your serializer takes precedence)
- if you want to make this change in a particular case, you can register a custom serializer/deserializer for the protobuf message which contains the `StringValue` field (rather than for `StringValue` itself)
